// client registeration/signup
export const CLIENT_REGISTER_REQUEST = 'CLIENT_REGISTER_REQUEST';
export const CLIENT_REGISTER_SUCCESS = 'CLIENT_REGISTER_SUCCESS';
export const CLIENT_REGISTER_FAIL = 'CLIENT_REGISTER_FAIL';

// auth
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const AUTH_USERNAME = 'AUTH_USERNAME';

// client signin
export const CLIENT_SIGNIN_REQUEST = 'CLIENT_SIGNIN_REQUEST';
export const CLIENT_SIGNIN_SUCCESS = 'CLIENT_SIGNIN_SUCCESS';
export const CLIENT_SIGNIN_FAIL = 'CLIENT_SIGNIN_FAIL';

// client logout
export const CLIENT_LOGOUT_REQUEST = 'CLIENT_LOGOUT_REQUEST';
export const CLIENT_LOGOUT_SUCCESS = 'CLIENT_LOGOUT_SUCCESS';
export const CLIENT_LOGOUT_FAIL = 'CLIENT_LOGOUT_FAIL';

// list of clients
export const CLIENT_LIST_REQUEST = 'CLIENT_LIST_REQUEST';
export const CLIENT_LIST_SUCCESS = 'CLIENT_LIST_SUCCESS';
export const CLIENT_LIST_FAIL = 'CLIENT_LIST_FAIL';

// client
export const CLIENT_REQUEST = 'CLIENT_REQUEST';
export const CLIENT_SUCCESS = 'CLIENT_SUCCESS';
export const CLIENT_FAIL = 'CLIENT_FAIL';

// client update
export const CLIENT_UPDATE_REQUEST = 'CLIENT_UPDATE_REQUEST';
export const CLIENT_UPDATE_SUCCESS = 'CLIENT_UPDATE_SUCCESS';
export const CLIENT_UPDATE_FAIL = 'CLIENT_UPDATE_FAIL';

// vaccines
export const VACCINE_ADD_REQUEST = 'VACCINE_ADD_REQUEST';
export const VACCINE_ADD_SUCCESS = 'VACCINE_ADD_SUCCESS';
export const VACCINE_ADD_FAIL = 'VACCINE_ADD_FAIL';

export const VACCINE_GET_REQUEST = 'VACCINE_GET_REQUEST';
export const VACCINE_GET_SUCCESS = 'VACCINE_GET_SUCCESS';
export const VACCINE_GET_FAIL = 'VACCINE_GET_FAIL';

export const VACCINE_LIST_REQUEST = 'VACCINE_LIST_REQUEST';
export const VACCINE_LIST_SUCCESS = 'VACCINE_LIST_SUCCESS';
export const VACCINE_LIST_FAIL = 'VACCINE_LIST_FAIL';
export const VACCINE_LIST_OPTIONS = 'VACCINE_LIST_OPTIONS';

export const VACCINE_REMOVE_REQUEST = 'VACCINE_REMOVE_REQUEST';
export const VACCINE_REMOVE_SUCCESS = 'VACCINE_REMOVE_SUCCESS';
export const VACCINE_REMOVE_FAIL = 'VACCINE_REMOVE_FAIL';

export const VACCINE_UPDATE_REQUEST = 'VACCINE_UPDATE_REQUEST';
export const VACCINE_UPDATE_SUCCESS = 'VACCINE_UPDATE_SUCCESS';
export const VACCINE_UPDATE_FAIL = 'VACCINE_UPDATE_FAIL';

// health facility
export const HEALTH_FACILITY_ADD_REQUEST = 'HEALTH_FACILITY_ADD_REQUEST';
export const HEALTH_FACILITY_ADD_SUCCESS = 'HEALTH_FACILITY_ADD_SUCCESS';
export const HEALTH_FACILITYE_ADD_FAIL = 'HEALTH_FACILITY_ADD_FAIL';

export const HEALTH_FACILITY_GET_REQUEST = 'HEALTH_FACILITY_GET_REQUEST';
export const HEALTH_FACILITY_GET_SUCCESS = 'HEALTH_FACILITY_GET_SUCCESS';
export const HEALTH_FACILITY_GET_FAIL = 'HEALTH_FACILITY_GET_FAIL';

export const HEALTH_FACILITY_UPDATE_REQUEST = 'HEALTH_FACILITY_UPDATE_REQUEST';
export const HEALTH_FACILITY_UPDATE_SUCCESS = 'HEALTH_FACILITY_UPDATE_SUCCESS';
export const HEALTH_FACILITY_UPDATE_FAIL = 'HEALTH_FACILITY_UPDATE_FAIL';

// appointment
export const APPOINTMENT_REQUEST = 'APPOINTMENT_REQUEST';
export const APPOINTMENT_SUCCESS = 'APPOINTMENT_SUCCESS';
export const APPOINTMENT_FAIL = 'APPOINTMENT_FAIL';

export const APPOINTMENT_LIST_REQUEST = 'APPOINTMENT_LIST_REQUEST';
export const APPOINTMENT_LIST_SUCCESS = 'APPOINTMENT_LIST_SUCCESS';
export const APPOINTMENT_LIST_FAIL = 'APPOINTMENT_LIST_FAIL';

export const APPOINTMENT_UPDATE_REQUEST = 'APPOINTMENT_UPDATE_REQUEST';
export const APPOINTMENT_UPDATE_SUCCESS = 'APPOINTMENT_UPDATE_SUCCESS';
export const APPOINTMENT_UPDATE_FAIL = 'APPOINTMENT_UPDATE_FAIL';
export const APPOINTMENT_EMAIL_REQUEST = 'APPOINTMENT_EMAIL_REQUEST';
