// constants are returned as action types which will be used in action and reducer files
// user
export const ADD_USER_TO_STORE = 'STORE.ADDUSER';
// product
export const ADD_PRODUCT_TO_STORE = 'STORE.ADDPRODUCT';
export const SET_PRODUCT_QTY = 'STORE.SETPRODUCTQTY';
export const DISPLAY_ALL_PRODUCT = 'STORE.DISPLAYPRODUCT';
export const REMOVE_SELECTED_PRODUCT = 'STORE.REMOVESELECTEDPRODUCT';
export const SELECT_PRODUCT = 'STORE.SELECTPRODUCT';
export const GET_PRODUCT_SUCCESS = 'STORE.GETPRODUCTSUCCESS';
export const GET_PRODUCT_FAILURE = 'STORE.GETPRODUCTFAILURE';
export const GET_PRODUCT_RESET = 'STORE.GETPRODUCTRESET';
export const GET_PRODUCT_REQUEST = 'STORE.GETPRODUCTREQUEST';
// update
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

export const GET_PRODUCT_DETAILS_SUCCESS = 'STORE.GETPRODUCTDETAILSSUCCESS';
export const GET_PRODUCT_DETAILS_FAILURE = 'STORE.GETPRODUCTDETAILSFAILURE';
export const GET_PRODUCT_DETAILS_RESET = 'STORE.GETPRODUCTDETAILSRESET';
export const GET_PRODUCT_DETAILS_REQUEST = 'STORE.GETPRODUCTDETAILSREQUEST';

// cart
export const ADD_TO_CART = 'STORE.ADDTOCART';
export const SHOW_CART = 'STORE.SHOWCART';
export const REMOVE_FROM_CART = 'STORE.REMOVEFROMCART';
export const RESET_CART = 'STORE.RESETCART';

// checkout
export const SHOW_CART_CHECKOUT = 'STORE.SHOWCARTCHECKOUT';

// login user
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// register user
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// update user
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

// coupon
export const COUPON_REQUEST = 'COUPON_REQUEST';
export const COUPON_SUCCESS = 'COUPON_SUCCESS';
export const COUPON_FAIL = 'COUPON_FAIL';
export const RESET_COUPON = 'COUPON_RESET';

// recentOrders
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';

// order status
export const SET_ORDER_STATUS_REQUEST = 'SET_ORDER_STATUS_REQUEST';
export const SET_ORDER_STATUS_SUCCESS = 'SET_ORDER_STATUS_SUCCESS';
export const SET_ORDER_STATUS_FAIL = 'SET_ORDER_STATUS_FAIL';

// recentOrdersList
export const RECENT_ORDERS_LIST_REQUEST = 'RECENT_ORDERS_LIST_REQUEST';
export const RECENT_ORDERS_LIST_SUCCESS = 'RECENT_ORDERS_LIST_SUCCESS';
export const RECENT_ORDERS_LIST_FAIL = 'RECENT_ORDERS_LIST_FAIL';
export const RECENT_ORDERS_LIST_DELIVERED = 'RECENT_ORDERS_LIST_DELIVERED';

// payment
export const CHECKOUT_PAYMENT_REQUEST = 'CHECKOUT_PAYMENT_REQUEST';
export const CHECKOUT_PAYMENT_SUCCESS = 'CHECKOUT_PAYMENT_SUCCESS';
export const CHECKOUT_PAYMENT_FAIL = 'CHECKOUT_PAYMENT_FAIL';

// reorder
export const REORDER_REQUEST = 'REORDER_REQUEST';
export const REORDER_SUCCESS = 'REORDER_SUCCESS';
export const REORDER_FAIL = 'REORDER_FAIL';

// logout user
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
